<a href="https://colab.research.google.com/github/ivansanchezflores921-web/ivan-sanchez-vanessa-cardenas-py-2PRACTICAS../blob/main/unidad_5_MN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np  # Importa NumPy para manejo de arreglos y operaciones

x = np.array([1, 2, 3])   # Define los valores de x conocidos
y = np.array([1, 4, 9])   # Define los valores de y correspondientes

n = len(x)  # Calcula el número de puntos

tabla = np.zeros((n, n))  # Inicializa la tabla de diferencias divididas

tabla[:, 0] = y  # Llena la primera columna con los valores de y

for j in range(1, n):  # Itera sobre las columnas de la tabla
    for i in range(n - j):  # Itera sobre las filas disponibles
        tabla[i, j] = (tabla[i + 1, j - 1] - tabla[i, j - 1]) / (x[i + j] - x[i])

print("Tabla de diferencias divididas:\n", tabla)  # Muestra la tabla

Tabla de diferencias divididas:
 [[1. 3. 1.]
 [4. 5. 0.]
 [9. 0. 0.]]


In [ ]:
import numpy as np

#Evaluacion de polinomio de newtoon

x = np.array([1,2,3]) #define los valores de x conocidos
y = np.array([1,4,9]) #define los valores de y correspondientes

n = len(x) #Calcula el numero de puntos
tabla = np.zeros((n,n)) #Inicializa la tabla de diferencias divididas


tabla[:,0] = y #Llena la primera columna con valores de y

for j in range(1,n): #Itera sobre las columnas de la tabla
  for i in range(n-j): #Itera sobre las filas disponibles
    tabla[i,j] = (tabla[i+1,j-1] - tabla[i,j-1])/(x[i+j] - x[i]) #calcula la diferencia


def newton_eval(x_data, tabla, x_val): #Define funcion para evaluar el polinomio
  n = len(x_data) #numero de puntos
  resultado = tabla[0,0] #Inicializa el primer coeficiente

  producto = 1 #Inicializa el producto acumulado

  for i in range(1,n): #Itera sobre terminos del polinomio
    producto *= (x_val - x_data[i-1]) #Calcula el termino (x-x_i)
    resultado += tabla[0,i]*producto #Suma el termino correspondiente

  return resultado #Retorna valor interpolado

valor = newton_eval(x,tabla,2.5) #Evalua el polinomio en x=2.5

print("Valor Interpolado:",valor) #Muestra resultado

Valor Interpolado: 6.25


In [ ]:
# interpolacion de datos
import numpy as np
x = np.array ([ 0 , 1 , 2 , 3 ]) # datos de entrada
y =  np.array ([1 , 2 , 0 , 5 ])# datos observados ( puedes ser incompletos o ruidoss)

n = len(x) #Calcula el numero de puntos
tabla = np.zeros((n,n)) #Inicializa la tabla de diferencias divididas

tabla[:,0] = y #Llena la primera columna con valores de y

for j in range(1,n): #Itera sobre las columnas de la tabla
  for i in range(n-j): #Itera sobre las filas disponibles
    tabla[i,j] = (tabla[i+1,j-1] - tabla[i,j-1])/(x[i+j] - x[i]) #calcula la diferencia


def newton_eval(x_data, tabla, x_val): #Define funcion para evaluar el polinomio
  n = len(x_data) #numero de puntos
  resultado = tabla[0,0] #Inicializa el primer coeficiente

  producto = 1 #Inicializa el producto acumulado

  for i in range(1,n): #Itera sobre terminos del polinomio
    producto *= (x_val - x_data[i-1]) #Calcula el termino (x-x_i)
    resultado += tabla[0,i]*producto #Suma el termino correspondiente

  return resultado #Retorna valor interpolado

x_interp = 1.5 # punto donde se quiere estimar el valor

y_interp = newton_eval (x, tabla , x_interp) #interpolacion

print("valor estimado:", y_interp ) # resultado final

valor estimado: 0.75


In [ ]:
import numpy as np # importa numpy para el manejo de datos numericos
from scipy.interpolate import CubicSpline # importa el cubuculo

x = np.array([0,1,2,3]) # define los puntos de el eje x
y = np.array([1,3,2,5])# define los valores correspondientes

spline = CubicSpline(x,y) # construye el spline cubico

x_interp = np.linspace(0,3,100) # genera 100 puntos para evaluar

y_interp = spline(x_interp) # evalua el spline en los puntos

print ("valores importados:", y_interp) # muestra valores

valores importados: [1.         1.17220877 1.33542959 1.48985725 1.63568653 1.77311221
 1.90232908 2.02353192 2.13691553 2.24267468 2.34100416 2.43209877
 2.51615327 2.59336246 2.66392112 2.72802404 2.78586601 2.8376418
 2.88354621 2.92377401 2.95852    2.98797896 3.01234568 3.03181494
 3.04658152 3.05684021 3.0627858  3.06461307 3.06251681 3.0566918
 3.04733283 3.03463468 3.01879215 3.         2.97845303 2.95434603
 2.92787378 2.89923106 2.86861266 2.83621337 2.80222797 2.76685125
 2.73027799 2.69270297 2.65432099 2.61532682 2.57591526 2.53628108
 2.49661908 2.45712404 2.41799074 2.37941397 2.34158852 2.30470917
 2.2689707  2.2345679  2.20169556 2.17054846 2.14132139 2.11420913
 2.08940646 2.06710818 2.04750907 2.03080391 2.01718749 2.00685459
 2.         1.99681851 1.99750489 2.00225394 2.01126045 2.02471918
 2.04282494 2.06577251 2.09375667 2.1269722  2.1656139  2.20987654
 2.25995492 2.31604382 2.37833802 2.44703231 2.52232147 2.60440029
 2.69346356 2.78970606 2.89332257 3.00450789

In [ ]:
import numpy as np # importa numpy

x = np.array([1,2,3,4,5,]) # define los puntos de el eje x
y = np.array([2,4,5,4,5])# define los valores correspondientes

coef = np.polyfit ( x,y,1) # ajusta un polinomio de grado

m = coef[0] # pendiente de la recta
b = coef [1] # interceccion en el eje y

y_pred = m*x + b # calcula los valores predichos por el momento

print ("pendiente:",m)# muestra la pendiente
print ("intercepto:",b ) # muestra el termino independiente
print ( "prediccion:",y_pred) # muestra los valores estimados

pendiente: 0.6000000000000001
intercepto: 2.1999999999999997
prediccion: [2.8 3.4 4.  4.6 5.2]


In [ ]:
import numpy as np # importa numpy

x = np.array([1,2,3,4,5,]) # define los puntos de el eje x
y = np.array([2,4,5,4,5])# define los valores correspondientes

correlacion = np.corrcoef (x,y)[0,1] #calcula el coeficiente
print("coeficiente de correlacion :", correlacion )# muestra resultados

coeficiente de correlacion : 0.7745966692414834
